### PR TITLE
Update to work with GitBook 3.2.0

### PR DESCRIPTION
**Pull request by dtolnay**

### CODE REVIEW

**Comment by dtolnay** [comment]
@litmon: warning, I don't know JavaScript or CSS so review carefully, but this seems to work.

**Comment by dtolnay** [comment]
Here it is in action: https://serde.rs/codegen-stable.html

**Comment by litmon** [comment]
looks good, thanks!
please bump up plugin version.

**Comment by dtolnay** [comment]
Bumped to 0.0.8.

**Comment by litmon** [comment]
thanks!

**Pull request merged**
